### ISSUE TITLE
Conversion of Jira Markup to Org has a bug with comments including square brackets

### ISSUE THREAD

**Issue by kat-co** [nyyManni/ejira#17] opened 2020-04-27 22:41 UTC
When I import tickets including these, the parser gets confused. In my case, the comment had a subsequent `*` and so an entire new top-level heading was created with the rest of the comment. This in turn disallowed refiling sub-tasks to their parents.

**Comment by nyyManni** [comment] 2020-04-28 16:06
Would you happen to have a sample jira markup file that produces this error so that I could validate any fix against it?

**Comment by MadEarl** [comment] 2020-05-08 21:31
I just stumbled over that problem as well. The text that triggered it was like 
```
- email@domain.invalid[mailto:email@domain.invalid] - somestring
- anotheremail@domain.invalid[mailto:anotheremail@domain.invalid] - someotherstring
```

If you cannot reproduce it, I can try and send a complete example.

**Comment by MadEarl** [comment] 2020-05-11 10:31
This is the exact string (names obfuscated) as retrieved by jiralib2-get-issue in the description field:

```
"Btsys ist eine XXX-Eigenentwicklung, d. h. entweder kann Solr direkt ersetzt werden, oder es wird eine Übersetzungsschicht entwickelt.

Testumgebung vorbereiten zum anprogrammiert werden.

User:

* Stanislav Bla [mailto:Stanislav.Blav@partner.domain.invalid] - qxo9988
* Mirza Foo [mailto:Mirza.Foo@partner.domain.invalid] - qxw9997
* Norbert Ra  [mailto:Norbert.Ra@partner.domain.invalid] - qxq9876
* Soenke Baz [mailto:Soenke.Bazt@partner.domain.invalid] - qxv1111

Auch Fgnrz-Demoumgebung freischalten?
"
```

It's probably related to some greedy matching? It also breaks the conversion of * to - so that the list items become top-level entries and end up partially in the next entry.

**Comment by chaorace** [comment] 2020-05-15 21:05
I'm able to reproduce the issue as well. Here's the affected description field:

```
+Screenshot Transcription+
* "Can we change this to network operations?" _As opposed to sending the email to FOOBAR directly, as this email was_
* "[Can we clean this ticket description up]?" _Verbatim: "?"_
* "[Why does this say Additional comments in a client-facing email]?" _Verbatim: "?"_

Referenced ticket: [FOOBAR|https://example.com]

(The ticket description issue has been split off into SE-XXX)
```

The org output is split into two parts:
* Normal Half
```
** TODO [#C] Update appearance of ticket update emails sent to customers
:PROPERTIES:
:ID:       SE-XXX
:TYPE:     ejira-story
:URL:      https://foobar.website/browse/SE-XXX
:Status:   To Do
:Reporter: FOOBAR
:Assignee:
:Issuetype: Story
:Epic:
:Created:  2020-03-13 14:44:58
:Modified: 2020-05-14 13:38:25
:END:
*** Description
+Screenshot Transcription+
- "Can we change this to network operations?" /As opposed to sending the email to FOOBAR directly, as this email was/
- "[[Can we clean this ticket description up]?" _Verbatim: "?"_
```
* Second half (split off, at the wrong header level near the end of the file):
```
** "[Why does this say Additional comments in a client-facing email]?" _Verbatim: "?"_

Referenced ticket: [FOOBAR|https://foobar.website]]

(The ticket description issue has been split off into SE-XXX)
```

@nyyManni Email me if you want to take a look at the full org output. I can't anonymize the whole file due to sheer size, but I'm happy to share more privately if it proves helpful for fixing this issue.

**Comment by chaorace** [comment] 2020-05-15 22:14
Pushed a PR that should resolve this issue, I no longer experience the weird splitting after starting with a fresh file.

@kat-co @MadEarl Can you folks test the new PR branch #22 and check if the issue is clear on your end as well? Keep in mind that you'll need to clear out the project org file and start fresh to see a difference.

**Comment by MadEarl** [comment] 2020-05-20 17:01
Fixes the biggest problem, org markup is no longer broken after update. I think I found a corner case where the square brackets are not correct yet, but have to confirm that. It's in any case a big improvement.

**Comment by vlcek** [comment] 2020-12-08 14:10
I had also similar issue caused by "confused" parser and the patch in PR fixed it for me.

Will the PR get merged anytime soon please? :)

**Closed** 2020-12-08 14:59 UTC
